### ISSUE TITLE
Feature request: working time 

### ISSUE THREAD

**Issue by Airmonkdev** [ITmaze/snapmaker-firmware#1]
Is it possible to add on the info page, or in a new maintenance page, of the touchscreen the total working hours of the machine? I think it will be very useful if we could have the n. of the hours the machine worked (printing, CNC, laser…) so that we can see if some maintenance is needed or not.
Also a reset button will be fine so that we could reset after maintenance or cleaning up or…

What do you think?

**Comment by vk6flab** [comment]
This request was added to the official SM issue tracker. Closing.

See: https://github.com/Snapmaker/Snapmaker2-Controller/issues/5

**Comment by ITmaze** [comment]
Third time lucky.

This issue was transferred to the official SM repository.

See: https://github.com/Snapmaker/Snapmaker2-Controller/issues/5
